version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    hostname: redis
    container_name: redis-dailyProject
    ports:
      - '6379:6379'

volumes:
  redis:
    driver: local

networks:
  mysqlnetwork:
    driver: bridge
